Added created_at to post_likes table
flarum/likes pull request #28
Opened 2021-05-10 07:44 UTC by glowingblue

Closes [flarum/core#2840](https://github.com/flarum/core/issues/2840)

2021-05-10 18:08 UTC, askvortsov1 requested changes
The migration file needs to be renamed to fit convention. Everything else works great, thanks!

2021-05-11 07:26 UTC, iPurpl3x commented
Oh, my bad @askvortsov1I guess I was too fast and overlooked that convention 🙈.
I hope it's good now.

2021-05-11 17:56 UTC, askvortsov1 approved these changes

2021-05-11 19:15 UTC, SychO9 approved these changes

2021-05-11 19:23 UTC, merged